export const products = [
    {
        name: 'US Polo Shirt 1',
        slug: 'us-polo-shirt-1',
        image: '/images/polo1.jpeg',
        category: 'tShirts',
        price: 599,
        countInStock: 10,
        brand: 'Us Polo',
        rating: 3.5,
        numReviews: 10,
        description: 'high quality tshirt'
    },
    {
        name: 'US Polo Shirt 2',
        slug: 'us-polo-shirt-2',
        category: 'tShirts',
        image: '/images/polo2.jpeg',
        price: 599,
        countInStock: 10,
        brand: 'Us Polo',
        rating: 3,
        numReviews: 10,
        description: 'high quality tshirt'
    },
    {
        name: 'US Polo Shirt 3',
        slug: 'us-polo-shirt-3',
        category: 'tShirts',
        image: '/images/polo3.jpeg',
        price: 599,
        countInStock: 10,
        brand: 'Us Polo',
        rating: 5,
        numReviews: 10,
        description: 'high quality tshirt'
    },
    {
        name: 'US Polo Shirt 4',
        slug: 'us-polo-shirt-4',
        category: 'tShirts',
        image: '/images/polo4.jpg',
        price: 599,
        countInStock: 10,
        brand: 'Us Polo',
        rating: 1,
        numReviews: 10,
        description: 'high quality tshirt'
    },
    {
        name: 'Nike Shoes 1',
        slug: 'nike-shoes-1',
        category: 'shoes',
        image: '/images/nike1.jpeg',
        price: 599,
        countInStock: 10,
        brand: 'nike',
        rating: 5,
        numReviews: 10,
        description: 'high quality shoes'
    },
    {
        name: 'Nike Shoes 2',
        slug: 'nike-shoes-2',
        category: 'shoes',
        image: '/images/nike2.jpg',
        price: 599,
        countInStock: 10,
        brand: 'nike',
        rating: 2.5,
        numReviews: 10,
        description: 'high quality shoes'
    },
    {
        name: 'Nike Shoes 3',
        slug: 'nike-shoes-3',
        category: 'shoes',
        image: '/images/nike3.jpeg',
        price: 599,
        countInStock: 10,
        brand: 'nike',
        rating: 1.5,
        numReviews: 10,
        description: 'high quality shoes'
    },
    {
        name: 'Nike Shoes 4',
        slug: 'nike-shoes-4',
        category: 'shoes',
        image: '/images/nike4.jpeg',
        price: 599,
        countInStock: 10,
        brand: 'nike',
        rating: 3.5,
        numReviews: 10,
        description: 'high quality shoes'
    },
    {
        name: 'iPhone 14 pro',
        slug: 'iPhone-14-pro',
        category: 'phone',
        image: '/images/phone1.jpeg',
        price: 80000,
        countInStock: 10,
        brand: 'apple',
        rating: 5,
        numReviews: 10,
        description: 'apple iPhone'
    },
    {
        name: 'Samsung Galaxy S23',
        slug: 'samsung-s23',
        category: 'phone',
        image: '/images/phone2.jpg',
        price: 60000,
        countInStock: 10,
        brand: 'samsung',
        rating: 4,
        numReviews: 10,
        description: 'Samsung Galaxy S23'
    },
    {
        name: 'OnePlus 11',
        slug: 'oneplus-11',
        category: 'phone',
        image: '/images/phone3.jpg',
        price: 50000,
        countInStock: 10,
        brand: 'OnePlus',
        rating: 4.5,
        numReviews: 10,
        description: 'OnePlus 11'
    },
    {
        name: 'Google Pixel 6',
        slug: 'pixel-6',
        category: 'phone',
        image: '/images/phone4.jpg',
        price: 50000,
        countInStock: 10,
        brand: 'samsung',
        rating: 4.5,
        numReviews: 10,
        description: 'Samsung Galaxy S23'
    },
]