export const products = [
    {
        id:1,
        name: 'US Polo Shirt 1',
        slug: 'us-polo-shirt-1',
        category: 'tShirts',
        image: '/images/polo1.jpeg',
        price: 599,
        countInStock: 10,
        brand: 'Us Polo',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality tshirt'
    },
    {
        id:2,
        name: 'US Polo Shirt 2',
        slug: 'us-polo-shirt-2',
        category: 'tShirts',
        image: '/images/polo2.jpeg',
        price: 599,
        countInStock: 10,
        brand: 'Us Polo',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality tshirt'
    },
    {
        id:3,
        name: 'US Polo Shirt 3',
        slug: 'us-polo-shirt-3',
        category: 'tShirts',
        image: '/images/polo3.jpeg',
        price: 599,
        countInStock: 10,
        brand: 'Us Polo',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality tshirt'
    },
    {
        id:4,
        name: 'US Polo Shirt 4',
        slug: 'us-polo-shirt-4',
        category: 'tShirts',
        image: '/images/polo4.jpg',
        price: 599,
        countInStock: 10,
        brand: 'Us Polo',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality tshirt'
    },
    // {
    //     name: 'Nike Shoes 1',
    //     slug: 'nike-shoes-1',
    //     category: 'shoes',
    //     image: '/images/nike1.jpeg',
    //     price: 599,
    //     countInStock: 10,
    //     brand: 'nike',
    //     rating: 4.5,
    //     numReviews: 10,
    //     description: 'high quality shoes'
    // },
    // {
    //     name: 'Nike Shoes 2',
    //     slug: 'nike-shoes-2',
    //     category: 'shoes',
    //     image: '/images/nike2.jpg',
    //     price: 599,
    //     countInStock: 10,
    //     brand: 'nike',
    //     rating: 4.5,
    //     numReviews: 10,
    //     description: 'high quality shoes'
    // },
    // {
    //     name: 'Nike Shoes 3',
    //     slug: 'nike-shoes-3',
    //     category: 'shoes',
    //     image: '/images/nike3.jpeg',
    //     price: 599,
    //     countInStock: 10,
    //     brand: 'nike',
    //     rating: 4.5,
    //     numReviews: 10,
    //     description: 'high quality shoes'
    // },
    // {
    //     name: 'Nike Shoes 4',
    //     slug: 'nike-shoes-4',
    //     category: 'shoes',
    //     image: '/images/nike4.jpeg',
    //     price: 599,
    //     countInStock: 10,
    //     brand: 'nike',
    //     rating: 4.5,
    //     numReviews: 10,
    //     description: 'high quality shoes'
    // },
]